# The configurations in this file are shared across all applications.

# Turns off security that Spring Cloud Services adds
# when it pulls in Spring Security
security:
  basic:
    enabled: false

# Turn off security of management endpoints
# for Spring Boot Actuator
management:
  security:
    enabled: false
